OPTIONS (SKIP=1)
    LOAD DATA
    CHARACTERSET UTF8
    INFILE 'departamentos.csv'
    INTO TABLE temporalmunicipios TRUNCATE
    FIELDS TERMINATED BY ';'
    OPTIONALLY ENCLOSED BY '"'
    TRAILING NULLCOLS
    (
    CODIGO_DEPARTAMENTO,
    NOMBRE_DEPARTAMENTO
    )